# Generated by Django 3.1.3 on 2020-11-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201021_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título del Post'),
        ),
    ]
