# Generated by Django 3.1.3 on 2020-11-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201115_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
    ]
