# Generated by Django 3.1.3 on 2020-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201115_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descripción'),
        ),
    ]
