# Generated by Django 3.1.3 on 2020-11-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201115_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='asunto',
        ),
    ]
