# Generated by Django 3.1.3 on 2020-11-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_contacto_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default='dfgdf', max_length=100, verbose_name='Asunto'),
            preserve_default=False,
        ),
    ]
