# Generated by Django 3.1.3 on 2020-11-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_contacto_asunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='asunto',
        ),
        migrations.AddField(
            model_name='contacto',
            name='telephone',
            field=models.CharField(max_length=10, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='Asunto'),
        ),
    ]
